repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: books-api
    labels:
      app: books-api
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    values:
      - values.yaml
      - image:
          tag: "{{ .StateValues.image.tag }}"
      - ingress:
          hostname: "{{ .StateValues.ingress.hostname }}"
      - extraSecretEnvVars:
          ConnectionStrings__DefaultConnection: "{{ .StateValues.extraSecretEnvVars.ConnectionStrings__DefaultConnection }}"
          AuthenticationOptions__PublicSigningKey: "{{ .StateValues.extraSecretEnvVars.AuthenticationOptions__PublicSigningKey }}"