// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225130400_AddKnowledgeAreasToBook")]
    partial class AddKnowledgeAreasToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookKnowledgeArea", b =>
                {
                    b.Property<long>("BooksId")
                        .HasColumnType("bigint");

                    b.Property<int>("KnowledgeAreasId")
                        .HasColumnType("integer");

                    b.HasKey("BooksId", "KnowledgeAreasId");

                    b.HasIndex("KnowledgeAreasId");

                    b.ToTable("BookKnowledgeArea");
                });

            modelBuilder.Entity("Core.Entities.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Annotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Core.Entities.BookCopy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BooksCopies");
                });

            modelBuilder.Entity("Core.Entities.BookCopyReadingHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualReturnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("BookCopyId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgressOfReading")
                        .HasColumnType("text");

                    b.Property<long>("ReaderEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ScheduledReturnDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.ToTable("BooksCopiesReadingHistory");
                });

            modelBuilder.Entity("Core.Entities.KnowledgeArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ML"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 5,
                            Name = "QA"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Design"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Business and Management"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Embedded"
                        },
                        new
                        {
                            Id = 9,
                            Name = "GameDev"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Information Security"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Copywriting and Editing"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Languages"
                        });
                });

            modelBuilder.Entity("BookKnowledgeArea", b =>
                {
                    b.HasOne("Core.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.KnowledgeArea", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeAreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.BookCopy", b =>
                {
                    b.HasOne("Core.Entities.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Core.Entities.BookCopyReadingHistory", b =>
                {
                    b.HasOne("Core.Entities.BookCopy", "BookCopy")
                        .WithMany("ReadingHistoryList")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");
                });

            modelBuilder.Entity("Core.Entities.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Core.Entities.BookCopy", b =>
                {
                    b.Navigation("ReadingHistoryList");
                });
#pragma warning restore 612, 618
        }
    }
}
