# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Checkout, build image, push it to the registry, deploy to production

on:
  push:
    branches:
      - master
  pull_request:    

jobs:
  run-unit-tests:
    name: Run unit-tests
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0  
        - name: Restore application dependencies
          run: dotnet restore 
        - name: Build application
          run: dotnet build
        - name: Run unit-tests
          run: dotnet test  

  build-and-push-to-registry:
    name: Build and push docker image to the packages
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
        - name: Check out the repo
          uses: actions/checkout@v4
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ghcr.io/tourmalinecore/inner-circle/books-api:${{ github.sha }}
  
  deploy-to-prod-k8s:
    needs: build-and-push-to-registry
    name: Deploy service to k8s for prod environment  
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            RELEASE_NAME=compensations-api
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm upgrade --install --namespace dev-inner-circle --create-namespace --values ./Api/ci/values-custom.yaml \
            --set "ingress.enabled=true" \
            --set "ingress.hostname=${{ secrets.HOST }}" \
            --set "image.tag=${{ github.sha }}" \
            --set "extraSecretEnvVars.ConnectionStrings__DefaultConnection=${{ secrets.POSTGRESQL_CONNECTION_STRING }}" \
            --set "extraSecretEnvVars.AuthenticationOptions__PublicSigningKey=${{ secrets.PUBLIC_SIGNING_KEY }}" \
            "${RELEASE_NAME}" \
            bitnami/aspnet-core --version 4.4.7
          kubeconfig: "${{ secrets.KUBECONFIG }}"